/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests. ## Authentication Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Annotation from './Annotation';

/**
 * The Comment model module.
 * @module model/Comment
 * @version 0.5.0
 */
class Comment {
    /**
     * Constructs a new <code>Comment</code>.
     * A Comment is a translator&#39;s or a reviewer&#39;s comment on a segment. 
     * @alias module:model/Comment
     */
    constructor() { 
        
        Comment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Comment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Comment} obj Optional instance to populate.
     * @return {module:model/Comment} The populated <code>Comment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Comment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('annotations')) {
                obj['annotations'] = ApiClient.convertToType(data['annotations'], [Annotation]);
            }
            if (data.hasOwnProperty('is_resolved')) {
                obj['is_resolved'] = ApiClient.convertToType(data['is_resolved'], 'Boolean');
            }
            if (data.hasOwnProperty('document_id')) {
                obj['document_id'] = ApiClient.convertToType(data['document_id'], 'Number');
            }
            if (data.hasOwnProperty('segment_id')) {
                obj['segment_id'] = ApiClient.convertToType(data['segment_id'], 'Number');
            }
            if (data.hasOwnProperty('segment_revision_id')) {
                obj['segment_revision_id'] = ApiClient.convertToType(data['segment_revision_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * A unique number identifying the Comment.
 * @member {Number} id
 */
Comment.prototype['id'] = undefined;

/**
 * The comment text.
 * @member {String} text
 */
Comment.prototype['text'] = undefined;

/**
 * A list of optional Annotations.
 * @member {Array.<module:model/Annotation>} annotations
 */
Comment.prototype['annotations'] = undefined;

/**
 * Whether the Comment is resolved.
 * @member {Boolean} is_resolved
 */
Comment.prototype['is_resolved'] = undefined;

/**
 * The document to which the comment belongs.
 * @member {Number} document_id
 */
Comment.prototype['document_id'] = undefined;

/**
 * The individual segment to which the comment applies.
 * @member {Number} segment_id
 */
Comment.prototype['segment_id'] = undefined;

/**
 * The revision of the individual segment to which the comment applies.
 * @member {Number} segment_revision_id
 */
Comment.prototype['segment_revision_id'] = undefined;

/**
 * The user who created this comment.
 * @member {Number} user_id
 */
Comment.prototype['user_id'] = undefined;

/**
 * Time at which the object was created. Measured in seconds since the Unix epoch.
 * @member {Number} created_at
 */
Comment.prototype['created_at'] = undefined;






export default Comment;

