/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  ## Authentication  Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentPretranslatingStatus from './DocumentPretranslatingStatus';

/**
 * The DocumentPretranslating model module.
 * @module model/DocumentPretranslating
 * @version 0.5.0
 */
class DocumentPretranslating {
    /**
     * Constructs a new <code>DocumentPretranslating</code>.
     * Document object for which pretranslation was requested. 
     * @alias module:model/DocumentPretranslating
     */
    constructor() { 
        
        DocumentPretranslating.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentPretranslating</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentPretranslating} obj Optional instance to populate.
     * @return {module:model/DocumentPretranslating} The populated <code>DocumentPretranslating</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentPretranslating();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('import_in_progress')) {
                obj['import_in_progress'] = ApiClient.convertToType(data['import_in_progress'], 'Boolean');
            }
            if (data.hasOwnProperty('import_succeeded')) {
                obj['import_succeeded'] = ApiClient.convertToType(data['import_succeeded'], 'Boolean');
            }
            if (data.hasOwnProperty('import_error_message')) {
                obj['import_error_message'] = ApiClient.convertToType(data['import_error_message'], 'String');
            }
            if (data.hasOwnProperty('is_processing')) {
                obj['is_processing'] = ApiClient.convertToType(data['is_processing'], 'Boolean');
            }
            if (data.hasOwnProperty('is_pretranslating')) {
                obj['is_pretranslating'] = ApiClient.convertToType(data['is_pretranslating'], 'Boolean');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = DocumentPretranslatingStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }


}

/**
 * A status object indicating the pretranslation status.
 * @member {Number} id
 */
DocumentPretranslating.prototype['id'] = undefined;

/**
 * Indicates that the document is being imported.
 * @member {Boolean} import_in_progress
 */
DocumentPretranslating.prototype['import_in_progress'] = undefined;

/**
 * Indicates that the document was successfully imported.
 * @member {Boolean} import_succeeded
 */
DocumentPretranslating.prototype['import_succeeded'] = undefined;

/**
 * Indicates there was an error importing the document.
 * @member {String} import_error_message
 */
DocumentPretranslating.prototype['import_error_message'] = undefined;

/**
 * Indicates the document is being processed.
 * @member {Boolean} is_processing
 */
DocumentPretranslating.prototype['is_processing'] = undefined;

/**
 * Indicates the document is being pretranslated.
 * @member {Boolean} is_pretranslating
 */
DocumentPretranslating.prototype['is_pretranslating'] = undefined;

/**
 * @member {module:model/DocumentPretranslatingStatus} status
 */
DocumentPretranslating.prototype['status'] = undefined;






export default DocumentPretranslating;

