/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  ## Authentication  Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentParameters model module.
 * @module model/DocumentParameters
 * @version 0.5.0
 */
class DocumentParameters {
    /**
     * Constructs a new <code>DocumentParameters</code>.
     * @alias module:model/DocumentParameters
     * @param name {String} The document name.
     * @param projectId {Number} A unique Project identifier.
     */
    constructor(name, projectId) { 
        
        DocumentParameters.initialize(this, name, projectId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, projectId) { 
        obj['name'] = name;
        obj['project_id'] = projectId;
    }

    /**
     * Constructs a <code>DocumentParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentParameters} obj Optional instance to populate.
     * @return {module:model/DocumentParameters} The populated <code>DocumentParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentParameters();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('project_id')) {
                obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The document name.
 * @member {String} name
 */
DocumentParameters.prototype['name'] = undefined;

/**
 * A unique Project identifier.
 * @member {Number} project_id
 */
DocumentParameters.prototype['project_id'] = undefined;






export default DocumentParameters;

