/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests. ## Authentication Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobStats from './JobStats';

/**
 * The Job model module.
 * @module model/Job
 * @version 0.5.0
 */
class Job {
    /**
     * Constructs a new <code>Job</code>.
     * A Job is a collection of multiple Projects. Each project is specific to a language pair, and is associated with exactly one Memory for that language pair. The Memory association cannot be changed after the Project is created. 
     * @alias module:model/Job
     */
    constructor() { 
        
        Job.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Job</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Job} obj Optional instance to populate.
     * @return {module:model/Job} The populated <code>Job</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Job();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('creationStatus')) {
                obj['creationStatus'] = ApiClient.convertToType(data['creationStatus'], 'String');
            }
            if (data.hasOwnProperty('deliveredAt')) {
                obj['deliveredAt'] = ApiClient.convertToType(data['deliveredAt'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('due')) {
                obj['due'] = ApiClient.convertToType(data['due'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('isProcessing')) {
                obj['isProcessing'] = ApiClient.convertToType(data['isProcessing'], 'Number');
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = JobStats.constructFromObject(data['stats']);
            }
        }
        return obj;
    }


}

/**
 * A name for the job.
 * @member {String} name
 */
Job.prototype['name'] = undefined;

/**
 * Status of job creation process that includes PENDING, COMPLETE, and FAILED.
 * @member {String} creationStatus
 */
Job.prototype['creationStatus'] = undefined;

/**
 * @member {Number} deliveredAt
 */
Job.prototype['deliveredAt'] = undefined;

/**
 * Current status of job that includes archived, delivered, and active.
 * @member {String} status
 */
Job.prototype['status'] = undefined;

/**
 * An ISO string date.
 * @member {String} due
 */
Job.prototype['due'] = undefined;

/**
 * An id for the job.
 * @member {Number} id
 */
Job.prototype['id'] = undefined;

/**
 * Values include `1` while in progress, `0` when idle and `-2` when processing failed.
 * @member {Number} isProcessing
 */
Job.prototype['isProcessing'] = undefined;

/**
 * @member {module:model/JobStats} stats
 */
Job.prototype['stats'] = undefined;






export default Job;

