/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests.  ## Authentication  Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use.  ## Quotas  Our services have a general quota of 4000 requests per minute. Should you hit the maximum requests per minute, you will need to wait 60 seconds before you can send another request. 
 *
 * The version of the OpenAPI document: v3.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LiltCreateContent model module.
 * @module model/LiltCreateContent
 * @version 0.6.3
 */
class LiltCreateContent {
    /**
     * Constructs a new <code>LiltCreateContent</code>.
     * Content Parameters for LiltCreate. 
     * @alias module:model/LiltCreateContent
     */
    constructor() { 
        
        LiltCreateContent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LiltCreateContent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LiltCreateContent} obj Optional instance to populate.
     * @return {module:model/LiltCreateContent} The populated <code>LiltCreateContent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LiltCreateContent();

            if (data.hasOwnProperty('tone')) {
                obj['tone'] = ApiClient.convertToType(data['tone'], 'String');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = ApiClient.convertToType(data['terms'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('memoryId')) {
                obj['memoryId'] = ApiClient.convertToType(data['memoryId'], 'String');
            }
            if (data.hasOwnProperty('sections')) {
                obj['sections'] = ApiClient.convertToType(data['sections'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The tone of the content.
 * @member {String} tone
 */
LiltCreateContent.prototype['tone'] = undefined;

/**
 * The terms of the content.
 * @member {String} terms
 */
LiltCreateContent.prototype['terms'] = undefined;

/**
 * The summary of the content.
 * @member {String} summary
 */
LiltCreateContent.prototype['summary'] = undefined;

/**
 * The language of the content.
 * @member {String} language
 */
LiltCreateContent.prototype['language'] = undefined;

/**
 * The memory ID of the content.
 * @member {String} memoryId
 */
LiltCreateContent.prototype['memoryId'] = undefined;

/**
 * The sections of the content.
 * @member {Array.<String>} sections
 */
LiltCreateContent.prototype['sections'] = undefined;






export default LiltCreateContent;

