/**
 * Lilt REST API
 * The Lilt REST API enables programmatic access to the full-range of Lilt backend services including:   * Training of and translating with interactive, adaptive machine translation   * Large-scale translation memory   * The Lexicon (a large-scale termbase)   * Programmatic control of the Lilt CAT environment   * Translation memory synchronization  Requests and responses are in JSON format. The REST API only responds to HTTPS / SSL requests. ## Authentication Requests are authenticated via REST API key, which requires the Business plan.  Requests are authenticated using [HTTP Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication). Add your REST API key as both the `username` and `password`.  For development, you may also pass the REST API key via the `key` query parameter. This is less secure than HTTP Basic Auth, and is not recommended for production use. 
 *
 * The version of the OpenAPI document: v2.0
 * Contact: support@lilt.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import TranslateRegisterResponse from '../model/TranslateRegisterResponse';
import TranslationList from '../model/TranslationList';

/**
* Translate service.
* @module api/TranslateApi
* @version v2.0
*/
export default class TranslateApi {

    /**
    * Constructs a new TranslateApi. 
    * @alias module:api/TranslateApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Register a segment
     * Register a source string for interactive translation. The `source_hash` value that is returned by this request is required by the `prefix` parameter for the translation endpoint. The maximum source length is 5,000 characters. Usage charges apply to this endpoint for production REST API keys.  
     * @param {String} source A source string to be registered.
     * @param {String} srclang An ISO 639-1 language code.
     * @param {String} trglang An ISO 639-1 language code.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TranslateRegisterResponse} and HTTP response
     */
    registerSegmentWithHttpInfo(source, srclang, trglang) {
      let postBody = null;
      // verify the required parameter 'source' is set
      if (source === undefined || source === null) {
        throw new Error("Missing the required parameter 'source' when calling registerSegment");
      }
      // verify the required parameter 'srclang' is set
      if (srclang === undefined || srclang === null) {
        throw new Error("Missing the required parameter 'srclang' when calling registerSegment");
      }
      // verify the required parameter 'trglang' is set
      if (trglang === undefined || trglang === null) {
        throw new Error("Missing the required parameter 'trglang' when calling registerSegment");
      }

      let pathParams = {
      };
      let queryParams = {
        'source': source,
        'srclang': srclang,
        'trglang': trglang
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TranslateRegisterResponse;
      return this.apiClient.callApi(
        '/translate/register', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Register a segment
     * Register a source string for interactive translation. The `source_hash` value that is returned by this request is required by the `prefix` parameter for the translation endpoint. The maximum source length is 5,000 characters. Usage charges apply to this endpoint for production REST API keys.  
     * @param {String} source A source string to be registered.
     * @param {String} srclang An ISO 639-1 language code.
     * @param {String} trglang An ISO 639-1 language code.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TranslateRegisterResponse}
     */
    registerSegment(source, srclang, trglang) {
      return this.registerSegmentWithHttpInfo(source, srclang, trglang)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Translate a segment
     * Translate a source string.  Setting the `rich` parameter to `true` will change the response format to include additional information about each translation including a model score, word alignments,  and formatting information. The rich format can be seen in the example response on this page.  By default, this endpoint also returns translation memory (TM) fuzzy matches, along with associated scores. Fuzzy matches always appear ahead of machine translation output in the response.  The maximum source length is 5,000 characters.  Usage charges apply to this endpoint for production REST API keys.  
     * @param {Number} memoryId A unique Memory identifier.
     * @param {Object} opts Optional parameters
     * @param {String} opts.source The source text to be translated.
     * @param {Number} opts.sourceHash A source hash code.
     * @param {String} opts.prefix A target prefix.
     * @param {Number} opts.n Return top n translations. (default to 1)
     * @param {Boolean} opts.rich Returns rich translation information (e.g., with word alignments). (default to false)
     * @param {Boolean} opts.tmMatches Include translation memory fuzzy matches. (default to true)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TranslationList} and HTTP response
     */
    translateSegmentWithHttpInfo(memoryId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'memoryId' is set
      if (memoryId === undefined || memoryId === null) {
        throw new Error("Missing the required parameter 'memoryId' when calling translateSegment");
      }

      let pathParams = {
      };
      let queryParams = {
        'memory_id': memoryId,
        'source': opts['source'],
        'source_hash': opts['sourceHash'],
        'prefix': opts['prefix'],
        'n': opts['n'],
        'rich': opts['rich'],
        'tm_matches': opts['tmMatches']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth', 'BasicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TranslationList;
      return this.apiClient.callApi(
        '/translate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Translate a segment
     * Translate a source string.  Setting the `rich` parameter to `true` will change the response format to include additional information about each translation including a model score, word alignments,  and formatting information. The rich format can be seen in the example response on this page.  By default, this endpoint also returns translation memory (TM) fuzzy matches, along with associated scores. Fuzzy matches always appear ahead of machine translation output in the response.  The maximum source length is 5,000 characters.  Usage charges apply to this endpoint for production REST API keys.  
     * @param {Number} memoryId A unique Memory identifier.
     * @param {Object} opts Optional parameters
     * @param {String} opts.source The source text to be translated.
     * @param {Number} opts.sourceHash A source hash code.
     * @param {String} opts.prefix A target prefix.
     * @param {Number} opts.n Return top n translations. (default to 1)
     * @param {Boolean} opts.rich Returns rich translation information (e.g., with word alignments). (default to false)
     * @param {Boolean} opts.tmMatches Include translation memory fuzzy matches. (default to true)
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TranslationList}
     */
    translateSegment(memoryId, opts) {
      return this.translateSegmentWithHttpInfo(memoryId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
